//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SyncIT.rc
//
#define IDS_CANNOT_START                1
#define IDS_HOSTNAME_ERR                2
#define IDS_SOCKET_ERR                  3
#define IDS_CONNECT_ERR                 4
#define IDS_STOPPING_WIN32              5
#define IDS_RUNNING                     6
#define IDS_BAD_RESPONSE                7
#define IDS_HTTP_RESPONSE               8
#define IDS_UNKNOWN_EMAIL               9
#define IDS_UNKNOWN_PASS                10
#define IDS_RETRY                       11
#define IDS_SERVER_ERROR                12
#define IDS_TEMPORARY_ERROR             13
#define IDS_TIP_DOWNLOAD                14
#define IDS_TIP_TEMPERR                 15
#define IDS_TIP_UPLOAD                  16
#define IDS_TIP_RETRY                   17
#define IDS_TIP_SYNCING                 18
#define IDS_TIP_LAST_SYNCED             19
#define IDS_STATE_DOWNLOAD              20
#define IDS_STATE_TEMPERR               21
#define IDS_LOGIN_ERR                   22
#define IDS_WIZARD_COUNT                23
#define IDS_NO_ERROR                    23
#define IDS_BOOKMARK_COUNT              24
#define IDS_PROXY_AUTO                  25
#define IDS_PROXY_HTTP                  26
#define IDS_PROXY_SOCKS                 27
#define IDS_PROXY_WININET               28
#define IDS_PROXY_DIRECT                29
#define IDS_PROXY_IE                    30
#define IDS_PROXY_NS                    31
#define IDS_SETTINGS_CAPTION            32
#define IDS_APP_UUID                    33
#define IDS_STATUS_CAPTION              34
#define IDS_REG_KEY                     35
#define IDS_FINISH                      36
#define IDS_NEXT                        37
#define IDS_TESTING                     38
#define IDS_INVALID_SETTINGS            39
#define IDS_STOPPING_IMPORT             40
#define IDS_NO_PROFILES                 41
#define IDS_DIR_ERR                     42
#define IDS_AOL_FILE_ERR                43
#define IDS_CHOOSE_NS                   44
#define IDS_FILE_ERR                    44
#define IDB_ABOUT                       101
#define IDD_ACCOUNT                     101
#define IDD_PRP_ACCOUNT                 101
#define IDM_POPUP                       102
#define IDD_BROWSERS                    102
#define IDD_IMP_FOLDER                  102
#define IDD_STATUS                      103
#define IDB_BOOKMARK                    104
#define APP_ICON                        105
#define IDD_IMP_DOING                   105
#define IDI_STALE                       106
#define IDD_IMP_FILE                    106
#define IDI_OPEN                        107
#define IDI_CLOSED                      108
#define IDI_BOOKMARK                    109
#define IDI_MAILTO                      110
#define IDD_INTRO                       111
#define IDD_REG_INTRO                   111
#define IDI_OPENSYNC                    112
#define IDD_ABOUT_BOX                   113
#define IDI_CLOSEDSYNC                  114
#define IDD_EMAIL                       115
#define IDD_REG_LOGIN                   115
#define IDD_PASSWORD                    116
#define IDD_REG_BROWSERS                116
#define IDD_READY                       117
#define IDD_REG_READY                   117
#define IDD_CONNECT                     118
#define IDD_REG_CONNECT                 118
#define IDD_PROXY                       119
#define IDD_WIZARD                      120
#define IDB_SYNCIT                      123
#define IDI_LIVE                        125
#define IDD_MERGE                       126
#define IDD_PROXY_SETTINGS              127
#define IDD_PRP_CONNECTION              127
#define IDD_DISPLAY                     128
#define IDD_PRP_DISPLAY                 128
#define IDB_ICON                        129
#define IDD_IMP_INTRO                   129
#define IDD_IMP_PROFILES                130
#define IDD_IMP_DIR                     131
#define IDB_BANNER                      132
#define IDB_FLAG                        134
#define IDD_BROWSE                      135
#define IDI_NEW_FOLDER                  136
#define IDD_ORGANIZE                    136
#define IDD_PRP_BROWSERS                137
#define IDB_RADIOMP3                    138
#define IDC_SYNCED                      1000
#define IDC_PROFILE                     1000
#define IDC_FOLDER                      1000
#define IDC_EMAIL                       1001
#define IDC_BROWSE                      1001
#define IDC_PASSWORD                    1002
#define IDC_PROFILES                    1002
#define IDC_STATUS                      1003
#define IDC_HAND                        1003
#define IDC_PROGRESS                    1003
#define IDC_WIZ_CONNECTING              1004
#define IDC_LIST1                       1004
#define IDC_DONE                        1004
#define IDC_WIZ_UPLOADING               1005
#define IDC_PROXY_CONFIG                1005
#define IDC_DIRECTORY                   1005
#define IDC_PROXY_ADDR                  1006
#define IDC_WIZ_DOWNLOADING             1007
#define IDC_PROXY_PORT                  1007
#define IDC_DONET                       1008
#define IDC_CONFIG_URL                  1008
#define IDC_DONEI                       1009
#define IDC_PROXY_TEST                  1009
#define IDC_MSG                         1010
#define IDC_ADDR_LBL                    1010
#define IDC_STATE                       1011
#define IDC_PORT_LBL                    1011
#define IDC_MSG0                        1012
#define IDC_CURL_LBL                    1012
#define IDC_WIZ_EMAIL                   1013
#define IDC_TEST_RESULTS                1013
#define IDC_SAVE                        1014
#define IDC_USERNAME                    1015
#define IDC_SERVER                      1016
#define IDC_REALM                       1017
#define IDC_NEXT                        1018
#define IDC_BACK                        1019
#define IDC_REGISTER                    1021
#define IDC_REGISTER2                   1022
#define IDC_WIZ_PASSWORD                1023
#define IDC_ENABLE_SYNC                 1024
#define ID_WIZ_CANCEL                   1025
#define ID_PROXY_CANCEL                 1026
#define ID_STATUS_DISMISS               1027
#define ID_PROXY_OK                     1028
#define IDC_VERSION                     1029
#define IDC_BOOKMARK_COUNT              1034
#define IDC_MERGE                       1035
#define IDC_CONNECT_SETTINGS            1036
#define IDC_USE_COLUMNS                 1037
#define IDC_TEST_ICON                   1038
#define IDC_CHECK1                      1039
#define IDC_NS                          1039
#define IDC_CHECK2                      1040
#define IDC_IE                          1040
#define IDC_CHECK3                      1041
#define IDC_OP                          1041
#define IDC_EDIT1                       1042
#define IDC_NS_DIR                      1042
#define IDC_EDIT2                       1043
#define IDC_IE_DIR                      1043
#define IDC_EDIT3                       1044
#define IDC_OP_DIR                      1044
#define IDC_BUTTON1                     1045
#define IDC_NS_CHANGE                   1045
#define IDC_NEW_FOLDER                  1045
#define IDC_BUTTON2                     1046
#define IDC_RADIO1                      1046
#define IDC_OP_CHANGE                   1046
#define IDC_IMP_AOL                     1046
#define IDC_RADIO2                      1047
#define IDC_IMP_OPERA                   1047
#define IDC_MERGE_CLR                   1047
#define IDC_RADIO3                      1048
#define IDC_IMP_NS                      1048
#define IDC_RADIO4                      1049
#define IDC_IMP_IE                      1049
#define IDC_RADIO5                      1050
#define IDC_IMP_XBEL                    1050
#define IDC_FILE                        1051
#define IDC_TREE                        1052
#define IDC_IMP_DIR_AOL                 1053
#define ID_POPUP_SYNCNOW                40001
#define ID_POPUP_AUTOSYNC               40002
#define ID_POPUP_STATUS                 40003
#define ID_POPUP_ABOUT                  40004
#define ID_POPUP_EXIT                   40005
#define ID_LOGIN                        40006
#define ID_POPUP_HELP                   40007
#define ID_HOMEPAGE                     40008
#define ID_RESETSYNCIT                  40009
#define ID_HOMEPAGE2                    40010
#define ID_SHUTDOWNSYNCIT               40011
#define ID_POPUP_ORGANIZE               40012
#define ID_POPUP_SETTINGS               40013
#define ID_POPUP_REFER                  40014
#define ID_POPUP_IMPORT                 40015
#define ID_POPUP_EXPORT                 40016
#define ID_BOOKMARK                     40100
#define ID_SUBSCRIPTION                 50100

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         40017
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
